[package]
name = "day-one"
version = "0.1.0"
authors = ["Richard Mayes <richard.mayes@watchfinder.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = '0.12.4'